#!/usr/bin/env python3
"""Regenerate SKILLS.md from each SKILL.md's frontmatter.

This removes SKILLS.md from the "things to update when adding a skill" checklist.
Adding a skill is now: drop a SKILL.md with valid frontmatter, run this script,
commit both. SKILLS.md becomes a derived artifact.

Examples:
  python scripts/build-skills-index.py            # write SKILLS.md
  python scripts/build-skills-index.py --check    # exit 1 if SKILLS.md is stale
  python scripts/build-skills-index.py --stdout   # print without writing
"""

import argparse
import re
import sys
from collections import defaultdict
from pathlib import Path

PHASE_ORDER = ["setup", "capture", "planning", "drafting", "review", "submission", "inspection"]
PHASE_TITLES = {
    "setup": "Setup (one-time + per-proposal bootstrap)",
    "capture": "Capture (pre-bid analysis)",
    "planning": "Planning and architecture",
    "drafting": "Drafting",
    "review": "Review",
    "submission": "Submission and post-submit",
    "inspection": "Inspection (read-only)",
}


def parse_frontmatter_with_comments(text: str) -> dict:
    """Parse frontmatter; also keep inline #comments per key (for 'don't use when' prose)."""
    text = text.replace("\r\n", "\n").lstrip("﻿")
    m = re.match(r"---\s*\n(.*?)\n---", text, re.DOTALL)
    if not m:
        return {}
    fm: dict = {}
    comments: dict[str, str] = {}
    for line in m.group(1).split("\n"):
        if not line.strip() or ":" not in line:
            continue
        # split off inline comment but preserve it
        comment_match = re.search(r"\s+#\s*(.+)$", line)
        comment = comment_match.group(1).strip() if comment_match else ""
        clean = line[: comment_match.start()] if comment_match else line
        k, _, v = clean.partition(":")
        v = v.strip()
        key = k.strip()
        if v.startswith("["):
            inner = v[1:].split("]", 1)[0].strip()
            v = [x.strip() for x in inner.split(",") if x.strip()]
        fm[key] = v
        if comment:
            comments[key] = comment
    fm["_comments"] = comments
    return fm


def first_sentence(text: str) -> str:
    if not text:
        return ""
    text = text.strip()
    m = re.match(r"^(.*?[.!?])\s", text)
    return m.group(1) if m else text


def dont_use_when(fm: dict) -> str:
    conflicts = fm.get("conflicts_with", []) or []
    if isinstance(conflicts, str):
        conflicts = []
    comment = fm.get("_comments", {}).get("conflicts_with", "")
    if not conflicts:
        return f"_(no peer — {comment})_" if comment else "_(no peer skill)_"
    if comment:
        # Prefer the human-authored rationale; the list itself is implicit
        return comment
    refs = ", ".join(f"`{c}`" for c in conflicts)
    return f"Conflicts with {refs}"


def composes_on(fm: dict) -> str:
    composes = fm.get("composes", []) or []
    if isinstance(composes, str):
        composes = []
    if not composes:
        return "—"
    return ", ".join(f"`{c}`" for c in composes)


def render_index(skills_dir: Path) -> str:
    skills: dict[str, dict] = {}
    for skill_md in sorted(skills_dir.glob("*/SKILL.md")):
        skills[skill_md.parent.name] = parse_frontmatter_with_comments(
            skill_md.read_text(encoding="utf-8-sig")
        )

    by_phase: defaultdict[str, list[str]] = defaultdict(list)
    for name, fm in skills.items():
        by_phase[fm.get("phase", "_unknown")].append(name)

    out: list[str] = []
    out.append("# Skill Index")
    out.append("")
    out.append("**Auto-generated by `scripts/build-skills-index.py`** from each SKILL.md's YAML frontmatter. Do not edit by hand — rerun the script after adding or changing a skill. CI / pre-commit can run `--check` to flag drift.")
    out.append("")
    out.append("Grouped by `phase`. Each row links to the authoritative `SKILL.md` and shows what the skill builds on (`composes`), when not to use it (paraphrased from `conflicts_with`), and a one-line description (first sentence of the SKILL's `description:` field).")
    out.append("")
    out.append("## Conventions captured in frontmatter")
    out.append("")
    out.append("Every SKILL.md declares: `name`, `description`, `phase`, `composes`, `conflicts_with`. Phase values: `setup`, `capture`, `planning`, `drafting`, `review`, `submission`, `inspection`. Validate the catalog with:")
    out.append("")
    out.append("```bash")
    out.append("python scripts/skill-graph.py --validate-only")
    out.append("python scripts/skill-graph.py --format mermaid > dependency-graph.md")
    out.append("```")
    out.append("")
    out.append("Activity is logged in each proposal's `working/activity.md` (no separate skill log). Aggregate across proposals with `python scripts/skill-stats.py`.")
    out.append("")

    for phase in PHASE_ORDER:
        members = sorted(by_phase.get(phase, []))
        if not members:
            continue
        out.append(f"## {PHASE_TITLES[phase]}")
        out.append("")
        out.append("| Skill | Composes on | Don't use when | What it does |")
        out.append("|---|---|---|---|")
        for name in members:
            fm = skills[name]
            desc = first_sentence(str(fm.get("description", "")))
            out.append(
                f"| [{name}](.claude/skills/{name}/SKILL.md) "
                f"| {composes_on(fm)} "
                f"| {dont_use_when(fm)} "
                f"| {desc} |"
            )
        out.append("")

    # Any phase that's not in PHASE_ORDER (e.g. _unknown)
    leftover = [p for p in by_phase if p not in PHASE_ORDER]
    if leftover:
        out.append("## (Skills with unrecognized phase)")
        out.append("")
        for p in leftover:
            for name in by_phase[p]:
                out.append(f"- `{name}` — phase {p!r}")
        out.append("")

    return "\n".join(out).rstrip() + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--skills-dir", default=".claude/skills")
    ap.add_argument("--out", default="SKILLS.md", help="Output path (default: SKILLS.md)")
    ap.add_argument("--check", action="store_true", help="Exit 1 if --out is stale relative to skills/")
    ap.add_argument("--stdout", action="store_true", help="Print to stdout instead of writing the file")
    args = ap.parse_args()

    skills_dir = Path(args.skills_dir)
    if not skills_dir.exists():
        print(f"No skills dir at {skills_dir}", file=sys.stderr)
        return 2

    rendered = render_index(skills_dir)

    if args.stdout:
        sys.stdout.write(rendered)
        return 0

    out_path = Path(args.out)
    current = out_path.read_text(encoding="utf-8") if out_path.exists() else ""

    if args.check:
        if current.strip() != rendered.strip():
            print(f"STALE: {out_path} differs from generated output. Run without --check to update.", file=sys.stderr)
            return 1
        print(f"OK: {out_path} is up to date")
        return 0

    out_path.write_text(rendered, encoding="utf-8")
    print(f"Wrote {out_path} ({len(rendered.splitlines())} lines, {len(list(skills_dir.glob('*/SKILL.md')))} skills)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
